apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lobby
  template:
    metadata:
      labels:
        app: lobby
    spec:
      containers:
      - name: lobby
        image: zyco/testargocd:latest
        ports:
        - containerPort: 80
        - containerPort: 443 # Ajoutez cette ligne pour le port HTTPS

